# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The Four Parameter Beta Distribution
#' 
#' @description Density, distribution function, quantile function and 
#'              random generation for the four parameter Beta distribution 
#'              with minimum value \code{min} and scale \code{scale}.
#'              
#' @details If \code{shape} is not specified, a default 
#'          value of 1 is used.
#'          
#'          The Birmbaum-Saunders distribution with shape \eqn{\beta} and
#'          scale \eqn{\theta} has density
#'          
#'          \deqn{f(x;\theta,\beta) = \frac{\sqrt{\frac{x}{\theta}}+\sqrt{\frac{\theta}{x}}}{2\beta x}\phi_{_{NOR}(z)},\quad x \ge 0 }
#'          
#'          where \eqn{\phi_{_{NOR}}(z)} is the density of the standard normal distribution and  
#'          
#'          \deqn{z = \frac{1}{\beta}\left(\sqrt{\frac{x}{\theta}}-\sqrt{\frac{\theta}{x} } \right)}.
#'          
#' @return \code{dbeta4} gives the density, 
#'         \code{pbeta4} gives the distribution function, 
#'         \code{qbeta4} gives the quantile function, and 
#'         \code{rbeta4} generates random observations.
#'         
#'         The length of the result is determined by \code{n} 
#'         for \code{rbeta4}, and is the maximum of the lengths 
#'         of the numerical arguments for the other functions. 
#'         
#'         The numerical arguments other than \code{n} are 
#'         recycled to the length of the result.   
#'          
#' @source Birnbaum, Z. W.; Saunders, S. C. (1969), "A new family of life distributions", Journal of Applied Probability, 6 (2): 319–327, JSTOR 3212003, doi:10.2307/3212003
#' @export
#' @rdname beta4
#' @name Four Parameter Beta
#' @param p Vector of probabilities
#' @param x Vector of quantiles
#' @param q Vector of quantiles
#' @param n Number of observations
#' @param min The minumum value on which the distribution is defined
#' @param max The maximum value on which the distribution is defined
#' @param shape1 Shape parameter
#' @param shape2 Shape parameter
#' @param gap Spacing from \code{min} and \code{max}
#' @export
dbeta4 <- function(x, min, max, shape1, shape2, gap = 0) {
    .Call('_OPER782_WI2020_dbeta4', PACKAGE = 'OPER782.WI2020', x, min, max, shape1, shape2, gap)
}

#' @export
#' @rdname beta4
#' @import RcppNumerical
pbeta4 <- function(q, min, max, shape1, shape2, gap = 0) {
    .Call('_OPER782_WI2020_pbeta4', PACKAGE = 'OPER782.WI2020', q, min, max, shape1, shape2, gap)
}

#' @export
#' @rdname beta4
qbeta4 <- function(p, min, max, shape1, shape2) {
    .Call('_OPER782_WI2020_qbeta4', PACKAGE = 'OPER782.WI2020', p, min, max, shape1, shape2)
}

#' @export
#' @rdname beta4
rbeta4 <- function(n, min, max, shape1, shape2) {
    .Call('_OPER782_WI2020_rbeta4', PACKAGE = 'OPER782.WI2020', n, min, max, shape1, shape2)
}

#' @export
timesTwo <- function(vec_in) {
    .Call('_OPER782_WI2020_timesTwo', PACKAGE = 'OPER782.WI2020', vec_in)
}

#' @export
NULL

psi_update <- function(PSI, PHI, Hp) {
    .Call('_OPER782_WI2020_psi_update', PACKAGE = 'OPER782.WI2020', PSI, PHI, Hp)
}

rcpp_hello_world <- function() {
    .Call('_OPER782_WI2020_rcpp_hello_world', PACKAGE = 'OPER782.WI2020')
}

